# Generated by Django 4.0.4 on 2022-04-29 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=50, verbose_name='Название на русском')),
                ('name_en', models.CharField(max_length=50, verbose_name='Название на английском')),
                ('name_local', models.CharField(max_length=50, verbose_name='Местное название')),
                ('code', models.CharField(blank=True, max_length=3, null=True, unique=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'db_table': 'district',
            },
        ),
        migrations.CreateModel(
            name='inspection_general',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено в')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=100, verbose_name='Manzil')),
                ('x_r', models.CharField(max_length=90, verbose_name='X/R')),
                ('sh_x', models.CharField(max_length=90, verbose_name='Sh.X')),
                ('bank', models.CharField(max_length=1000, verbose_name='Toshkent shaxar Markaziybank')),
                ('mfo', models.CharField(max_length=50, verbose_name='MFO')),
                ('oked', models.CharField(max_length=500, verbose_name='OKED')),
                ('inn', models.CharField(max_length=15, verbose_name='INN')),
                ('phone_number', models.CharField(max_length=9, verbose_name='Telefon')),
            ],
        ),
        migrations.CreateModel(
            name='product_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=500)),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено в')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=512, verbose_name='Название регион')),
                ('name_en', models.CharField(max_length=512, verbose_name='Name of region')),
                ('name_uz', models.CharField(max_length=512, null=True, verbose_name='Viloyat nomi')),
                ('coefficient', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('limit', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Regions',
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='type_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=500)),
                ('value', models.FloatField()),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено в')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_number', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='Номер Оферта')),
                ('given_date', models.DateField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('cadastre_number', models.IntegerField()),
                ('square_of_services', models.FloatField(default=0, verbose_name='Количество')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, verbose_name='Сумма платежа')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Оплаченное количество')),
                ('applicant_organization', models.CharField(max_length=128, null=True, verbose_name='Организация')),
                ('applicant_tin', models.CharField(max_length=15, null=True, verbose_name='ИНН/ПИНФЛ заявителя')),
                ('applicant_fullname', models.CharField(max_length=60, null=True, verbose_name='ФИО заявителя')),
                ('applicant_phone', models.CharField(max_length=9, null=True, verbose_name='Телефонный номер')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено в')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contract_app.district', verbose_name='Код дистрикт заявителя')),
                ('general_inspection', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contract_app.inspection_general', verbose_name='Директор')),
                ('product_type', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_type', to='contract_app.product_type', verbose_name='product_type')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contract_app.region', verbose_name='Код региона заявителя')),
                ('service_type', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='service_type', to='contract_app.type_service', verbose_name='Service Type')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='contract_app.region', verbose_name='Область'),
        ),
    ]
