# Generated by Django 4.0.4 on 2022-05-03 18:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_app', '0002_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Point(longitude latitude)', null=True, srid=4326, verbose_name='Location in Map'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='image',
            field=models.ImageField(blank=True, upload_to='qrcode/'),
        ),
    ]
