# Generated by Django 4.0.4 on 2022-05-03 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract_app', '0003_oferta_location_alter_qrcode_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oferta',
            old_name='location',
            new_name='adress_location',
        ),
    ]
