# Generated by Django 4.0.4 on 2022-05-03 19:27

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract_app', '0004_rename_location_oferta_adress_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='adress_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
